--ORDENA LAS PELÍCULAS POR DURACIÓN DE FORMA ASCENDENTE


SELECT "title" AS "TÍTULO PELÍCULA",
        "length" AS "DURACIÓN PELICULA"
FROM "film" AS f
GROUP BY "TÍTULO PELÍCULA","DURACIÓN PELICULA" 
ORDER BY "DURACIÓN PELICULA" 