--ENCUENTRA LA CANTIDAD TOTAL DE PELICULAS EN CADA CLASIFICACIÓN DE LA TABLA FILM Y MUESTRA LA CLASIFICACIÓN JUNTO CON EL RECUENTO

SELECT f."rating"  AS "CLASIFICACIÓN",
       COUNT (f."rating") AS "TOTAL DE PELÍCULAS"  
FROM "film" AS f
GROUP BY "CLASIFICACIÓN" 