--ENCUENTRA EL PROMEDIO DE DURACIÓN DE LAs PELÍCULAS PARA CADA CLASIFICACIÓN DE LA TABLA FILM Y MUESTRA LA CLASIFICACIÓN JUNTO CON EL PROMEDIO DE DURACIÓN

SELECT ROUND( AVG(f."length"),2) AS "PROMEDIO DURACIÓN",
		f."rating" AS "CLASIFICACIÓN"	
FROM "film" AS f
GROUP BY f."rating"
ORDER BY "PROMEDIO DURACIÓN" DESC 