--ENCUENTRA EL PROMEDIO, LA DESVIACIÓN ESTANDAR Y VARIANZA DEL TOTAL PAGADO

--Hago subconsulta en FROM que es sobre lo que quiero aplicar filtro

SELECT ROUND (AVG("TOTAL PAGADO"),2)AS "PROMEDIO PAGADO",
		ROUND (STDDEV ("TOTAL PAGADO"),2) AS "VARIACIÓN RESPECTO A LA MEDIA DEL PAGADO",
		ROUND (VARIANCE ("TOTAL PAGADO"),2)AS "DESVIACIÓN DEL TOTAL PAGADO"
FROM (SELECT SUM("amount")AS "TOTAL PAGADO"
	  FROM "payment" AS p
	  GROUP BY "customer_id")