--SELECCIONA TODOS LOS ACTORES Y ORDÉNALOS POR APELLIDO EN ORDEN ASCENDENTE


SELECT CONCAT(a."first_name",' ',a."last_name") AS "NOMBRE Y APELLIDOS ACTORES"
FROM "actor" AS a
ORDER BY "last_name" ASC 
