--REALIZA UN CROSS JOIN ENTRE LAS TABLAS FILM Y CATEGORY. ¿APORTA VALOR ESTA CONSULTA? ¿POR QUE? DEJA DESPUÉS DE LA CONSULTA LA CONTESTACIÓN


SELECT f."title"AS "TITULO",
		c."name" AS "NOMBRE CATEGORÍA"
FROM"film"AS f
CROSS JOIN "category"AS c

--NO APORTA VALOR PARA ANALIZAR NADA
--CONSULTA DONDE COMBINAMOS CADA FILA DE LA TABLA FILM CON TODAS LAS FILAS DE LA OTRA TABLA CATEGORY, AUNQUE NO EXISTE NINGUNA RELACIÓN

