--CREA UNA VISTA LLAMADA "ACTOR_NUM_PELICULAS" QUE MUESTRE LOS NOMBRES DE LOS ACTORES Y EL NUMERO DE PELÍCULAS EN LAS QUE HAN PARTICIPADO



--CREO LA VISTA (es la misma consulta 47)
CREATE VIEW "ACTOR_NUM_PELICULAS" AS
SELECT CONCAT(a."first_name",' ', a."last_name") AS "ACTOR",
		COUNT (fa."film_id") AS "CONTEO DE PELÍCULAS"
FROM "actor" AS a
INNER JOIN "film_actor" AS fa
ON a."actor_id"= fa."actor_id"
GROUP BY a."first_name",
		 a."last_name"
ORDER BY "CONTEO DE PELÍCULAS" 


--HAGO CONSULTA
SELECT *
FROM "ACTOR_NUM_PELICULAS" AS anp 
ORDER BY "CONTEO DE PELÍCULAS"