--ENCUENTRA LA CANTIDAD TOTAL DE PELÍCULAS ALQUILADAS POR CADA CLIENTE Y MUESTRA EL ID DEL CLIENTE, SU NOMBRE Y APELLIDO JUNTO CON LA CANTIDAD DE PELÍCULAS ALQUILADAS



SELECT c."customer_id" AS "ID CLIENTE",
		CONCAT (c."first_name",' ', c."last_name") as "CLIENTE",
		COUNT (r."rental_id") AS "CONTEO ALQUILERES"
FROM "customer" AS c
INNER JOIN "rental" AS r
ON c."customer_id"= r."customer_id"
GROUP BY c."customer_id","CLIENTE" 
ORDER BY "CLIENTE","CONTEO ALQUILERES", "ID CLIENTE" 


